version: "2"

services:
  datasource-gw:
    image: ty2/datasource-gw:dev
    env_file:
      - docker-compose.env
    ports:
      - "9901:80"
  binance-datasource:
    image: ty2/binance-datasource:dev
    ports:
      - "9902:80"
    env_file:
      - docker-compose.env
  influxdb-datasource:
    image: ty2/influxdb-datasource:dev
    ports:
      - "9903:80"
    env_file:
      - docker-compose.env
  price-periodic-collector:
    image: ty2/price-periodic-collector:dev
    env_file:
      - docker-compose.env
    depends_on:
      - binance-datasource